name: Update Market Data

on:
  workflow_dispatch:
  schedule:
    - cron: "*/30 * * * *"

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install node-fetch

      - name: Run script
        run: node update.js

      - name: Commit changes
        run: |
          git config user.name "bot"
          git config user.email "bot@test.com"
          git pull --rebase
          git add data.json
          git commit -m "update data" || exit 0
          git push
